<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKACMUaQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKACMUaQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKACMUaQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKACMUaQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKACMUaQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'KACMUaQ',
    'container.build_id' => 'b767e3cd',
    'container.build_time' => 1679533060,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKACMUaQ');
