<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7j5Dydt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7j5Dydt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7j5Dydt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7j5Dydt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7j5Dydt\App_KernelDevDebugContainer([
    'container.build_hash' => '7j5Dydt',
    'container.build_id' => '9c99e0e0',
    'container.build_time' => 1677896436,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7j5Dydt');
